### ISSUE TITLE
Trouble building on target  `i686-pc-windows-msvc`

### ISSUE THREAD

**Issue by shashwat1002** [zmwangx/rust-ffmpeg-sys#42]
On trying to setup with windows, the following error is observed 

` EXEC : error : failed to run custom build command for `ffmpeg-sys-next v5.0.1`

I observed this error as part of a continuous integration build fail on windows. 

url: https://github.com/CCExtractor/ccextractor/runs/7147475795?check_suite_focus=true

**Comment by abdoei** [comment]
The build job log -attached to the link- is no longer available
can you fix this

**Comment by prateekmedia** [comment]
Fixed this issue in ccextractor but another issue is coming which is related to channel_layout.h header,  i.e. https://github.com/zmwangx/rust-ffmpeg-sys/issues/51

**Comment by amrmostafa800** [comment]
![image](https://github.com/zmwangx/rust-ffmpeg-sys/assets/20041519/259deea6-2202-4059-a2d5-3704aba9f24a)
Its Build Normal When I Test (i build from windows)
using LLVM 32 bit libclang

**Comment by sabinonweb** [comment]
So I tried to fix this on mac. I ran the command "brew install ffmpeg" and the code now gets built. I don't understand, is it running because ffmpeg is installed onto my machine or is that the way?

**Comment by Ni1esh-Yadav** [comment]
Hello, Is the issue still persist?? Cause In my System it is building succesfully I am using windows 11, I am asking Because the author has not mentioned the steps to reproduce.

**Comment by Ni1esh-Yadav** [comment]
initially it do throw me the error but it was not related to the code it was related to the setup Please reply me so that I get some insight>
